### ISSUE TITLE
Video is recorded incomplete on failed tests

### ISSUE THREAD

**Issue by adolgoff** [thinktecture-labs/article-e2e-testing-cypress-angular#1]
Could I kindly ask you to confirm if the case with Cypress 6.0.0 is reproducible in your environment?

### Current behavior: 
Video is recorded incomplete (only a second after a test case start) and useless

### Expected behavior
Full video of failed test is recorded

### Steps to reproduce
1. Write incorrect test in specs.ts
2. Run `npm run e2e:ci`
3. Check mp4 video contained in `cypress/videos` folder.

If the issue is reproducible please vote for the fix here
[https://github.com/cypress-io/cypress/issues/9367](https://github.com/cypress-io/cypress/issues/9367)

**Comment by konstantindenerz** [comment]
The current repository uses https://github.com/briebug/cypress-schematic. The latest version references the ^5.1.0 version of Cypress. That's why it works with the current repository. There is already a PR for the update: https://github.com/briebug/cypress-schematic/pull/79

I can confirm the recording issue with cypress@6.0.0 & Electron 87 on macOS. The video takes the same time as the `cypress open` command, but the content of the tests is not displayed. I see this static picture the whole time:
![image](https://user-images.githubusercontent.com/1221055/100539462-e960f380-3236-11eb-85b9-8e02392175d0.png)
